package com.example.demo.entity;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.menu.id
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.menu.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    private String menu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.menu.id
     *
     * @return the value of public.menu.id
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.menu.id
     *
     * @param id the value for public.menu.id
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.menu.menu
     *
     * @return the value of public.menu.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    public String getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.menu.menu
     *
     * @param menu the value for public.menu.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    public void setMenu(String menu) {
        this.menu = menu;
    }
}