package com.example.demo.entity;

public class Purpose {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.purpose.id
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.purpose.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    private String purpose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.purpose.id
     *
     * @return the value of public.purpose.id
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.purpose.id
     *
     * @param id the value for public.purpose.id
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.purpose.purpose
     *
     * @return the value of public.purpose.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.purpose.purpose
     *
     * @param purpose the value for public.purpose.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
}