package com.example.demo.entity;

public class Rsv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rsv.id
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rsv.date
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rsv.time
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rsv.count_heads
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    private Integer countHeads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rsv.purpose
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    private String purpose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rsv.id
     *
     * @return the value of public.rsv.id
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rsv.id
     *
     * @param id the value for public.rsv.id
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rsv.date
     *
     * @return the value of public.rsv.date
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rsv.date
     *
     * @param date the value for public.rsv.date
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rsv.time
     *
     * @return the value of public.rsv.time
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rsv.time
     *
     * @param time the value for public.rsv.time
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rsv.count_heads
     *
     * @return the value of public.rsv.count_heads
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public Integer getCountHeads() {
        return countHeads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rsv.count_heads
     *
     * @param integer the value for public.rsv.count_heads
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public void setCountHeads(Integer integer) {
        this.countHeads = integer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rsv.purpose
     *
     * @return the value of public.rsv.purpose
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rsv.purpose
     *
     * @param purpose the value for public.rsv.purpose
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
}