package com.example.demo.mapper;

import com.example.demo.entity.Menu;
import com.example.demo.entity.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    long countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    Menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.menu
     *
     * @mbg.generated Sat Jan 21 02:10:04 JST 2023
     */
    int updateByPrimaryKey(Menu record);
}