package com.example.demo.mapper;

import com.example.demo.entity.Purpose;
import com.example.demo.entity.PurposeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    long countByExample(PurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int deleteByExample(PurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int insert(Purpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int insertSelective(Purpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    List<Purpose> selectByExample(PurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    Purpose selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int updateByExampleSelective(@Param("record") Purpose record, @Param("example") PurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int updateByExample(@Param("record") Purpose record, @Param("example") PurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int updateByPrimaryKeySelective(Purpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.purpose
     *
     * @mbg.generated Tue Feb 07 11:10:54 JST 2023
     */
    int updateByPrimaryKey(Purpose record);
}