package com.example.demo.mapper;

import com.example.demo.entity.Rsv;
import com.example.demo.entity.RsvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RsvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    long countByExample(RsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int deleteByExample(RsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int insert(Rsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int insertSelective(Rsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    List<Rsv> selectByExample(RsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    Rsv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int updateByExampleSelective(@Param("record") Rsv record, @Param("example") RsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int updateByExample(@Param("record") Rsv record, @Param("example") RsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int updateByPrimaryKeySelective(Rsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rsv
     *
     * @mbg.generated Tue Feb 07 11:24:50 JST 2023
     */
    int updateByPrimaryKey(Rsv record);
}